<a href="https://colab.research.google.com/github/ccunique/ds_code_examples/blob/main/Graph/GNN/graph_env_setting_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Wed Oct 25 01:41:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# install torch, dgl, pyG, pygod

## torch 2.0.1+cu118
need torch 2.0.1, if 2.1.0 dgl sparse will not work

In [ ]:
!pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 GB 494.1 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 106.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 105.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.3/132.3 kB 16.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for lit: filename=lit-15.0.7-py3-none-any.whl size=89989 sha256=41f4e3e72cb8586c0d3eaa00b1084f6c03ec8e8aeea54561c23e6279607729e2
  Stored in directory: /root/.cache/pip/wheels/27/2c/b6/3ed2983b1b44fe0dea1bb35234b09f2c22fb8ebb308679c922
Successfully built lit
  Attempting uninstall: triton
    Found existing installation: triton 2.1.0
    Uninstalling triton-2.1.0:
      Successfully uninstalled triton-2.1.0
  Attempting uninstall: torch
    Found existing installation: torch 2

## dgl

In [ ]:
!pip install dgl -f https://data.dgl.ai/wheels/cu118/repo.html

Looking in links: https://data.dgl.ai/wheels/cu118/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.3/91.3 MB 9.4 MB/s eta 0:00:00


## pyG series

In [ ]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 16.5 MB/s eta 0:00:00


In [ ]:
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cu118.html

Looking in links: https://data.pyg.org/whl/torch-2.0.0+cu118.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 65.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 886.6/886.6 kB 59.6 MB/s eta 0:00:00


## pygod

In [ ]:
!pip install pygod

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pygod: filename=pygod-1.0.0-py3-none-any.whl size=70678 sha256=827245e209c42700e48679ac4fcfe9e3c95a7c3432aa21644b2d64a02d5797b4
  Stored in directory: /root/.cache/pip/wheels/19/4f/5e/d4a08c3476915cb8021462fe4129680c598ebce8b100f59ecf
Successfully built pygod


# version summary

In [ ]:
import sys
# python >= 3.8
sys.version

'3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'

In [ ]:
import torch

print(torch.__name__,' version:', torch.__version__)

torch  version: 2.0.1+cu118


In [ ]:
import dgl

print(dgl.__name__,' version:', dgl.__version__)

DGL backend not selected or invalid.  Assuming PyTorch for now.


Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
dgl  version: 1.1.2+cu118


In [ ]:
# torch_geometric
import pyg_lib
import torch_scatter
import torch_sparse
import torch_cluster
import torch_spline_conv
import torch_geometric

for lib in [pyg_lib, torch_scatter, torch_sparse, torch_cluster, torch_spline_conv, torch_geometric]:
  print(lib.__name__,' version:', lib.__version__)

pyg_lib  version: 0.3.0+pt20cu118
torch_scatter  version: 2.1.2+pt20cu118
torch_sparse  version: 0.6.18+pt20cu118
torch_cluster  version: 1.6.3+pt20cu118
torch_spline_conv  version: 1.2.2+pt20cu118
torch_geometric  version: 2.4.0


In [ ]:
import pygod

print(pygod.__name__,' version:', pygod.__version__)

pygod  version: 1.0.0


# test DGL on gpu

## dgl sparse

In [ ]:
# test dglsp
import dgl.sparse as dglsp

import torch
import torch.nn as nn
import torch.nn.functional as F

import dgl.sparse as dglsp

import numpy as np

u, v = torch.tensor([0, 0, 0, 1, 1]), torch.tensor([1, 2, 3, 3, 3])
g = dgl.graph((u, v))
print(g)
print(g.nodes())
print(g.edges())
print(g.edges(form='all'))
g = dgl.graph((u, v), num_nodes=4)

g.ndata['feat']=torch.tensor(np.random.rand(4,20), dtype=torch.float32)
g.ndata["label"]=torch.tensor(np.random.randint(0,2,(4,)))
g.ndata['train_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g.ndata['val_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g.ndata['test_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g = dgl.add_self_loop(g)


class GCNLayer(nn.Module):
    def __init__(self, in_size, out_size):
        super(GCNLayer, self).__init__()
        self.W = nn.Linear(in_size, out_size)

    def forward(self, A, X):
        ########################################################################
        # (HIGHLIGHT) Compute the symmetrically normalized adjacency matrix with
        # Sparse Matrix API
        ########################################################################
        # I = dglsp.identity(A.shape).cuda() # why identity not move to cuda with model
        I = dglsp.identity(A.shape, device=A.device) # identity need manully move to cuda based on A.device

        A_hat = A + I
        D_hat = dglsp.diag(A_hat.sum(0))
        D_hat_invsqrt = D_hat ** -0.5
        return D_hat_invsqrt @ A_hat @ D_hat_invsqrt @ self.W(X)

# Create a GCN with the GCN layer.
class GCN(nn.Module):
    def __init__(self, in_size, out_size, hidden_size):
        super(GCN, self).__init__()
        self.conv1 = GCNLayer(in_size, hidden_size)
        self.conv2 = GCNLayer(hidden_size, out_size)

    def forward(self, A, X):
        X = self.conv1(A, X)
        X = F.relu(X)
        return self.conv2(A, X)


def train(g, model):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    best_val_acc = 0
    best_test_acc = 0

    features = g.ndata["feat"]
    labels = g.ndata["label"]
    train_mask = g.ndata["train_mask"]
    val_mask = g.ndata["val_mask"]
    test_mask = g.ndata["test_mask"]

    # Preprocess to get the adjacency matrix of the graph.
    indices = torch.stack(g.edges())
    N = g.num_nodes()
    A = dglsp.spmatrix(indices, shape=(N, N))

    for e in range(100):
        # Forward
        logits = model(A, features)

        # Compute prediction
        pred = logits.argmax(1)

        # Compute loss
        # Note that you should only compute the losses of the nodes in the training set.
        loss = F.cross_entropy(logits[train_mask], labels[train_mask])

        # Compute accuracy on training/validation/test
        train_acc = (pred[train_mask] == labels[train_mask]).float().mean()
        val_acc = (pred[val_mask] == labels[val_mask]).float().mean()
        test_acc = (pred[test_mask] == labels[test_mask]).float().mean()

        # Save the best validation accuracy and the corresponding test accuracy.
        if best_val_acc < val_acc:
            best_val_acc = val_acc
            best_test_acc = test_acc

        # Backward
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if e % 5 == 0:
            print(
                f"In epoch {e}, loss: {loss:.3f}, val acc: {val_acc:.3f} (best {best_val_acc:.3f}), test acc: {test_acc:.3f} (best {best_test_acc:.3f})"
            )

# # train on cpu
# model = GCN(g.ndata["feat"].shape[1], 2, 16)
# train(g, model)

# train on gpu
g = g.to('cuda')
model = GCN(g.ndata["feat"].shape[1], 2, 16).to('cuda')
train(g, model)


Graph(num_nodes=4, num_edges=5,
      ndata_schemes={}
      edata_schemes={})
tensor([0, 1, 2, 3])
(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 3, 3]))
(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 3, 3]), tensor([0, 1, 2, 3, 4]))
In epoch 0, loss: 0.635, val acc: 0.750 (best 0.750), test acc: 0.667 (best 0.667)
In epoch 5, loss: 0.571, val acc: 0.750 (best 0.750), test acc: 0.667 (best 0.667)
In epoch 10, loss: 0.517, val acc: 0.750 (best 0.750), test acc: 0.667 (best 0.667)
In epoch 15, loss: 0.427, val acc: 0.750 (best 0.750), test acc: 0.667 (best 0.667)
In epoch 20, loss: 0.314, val acc: 0.750 (best 0.750), test acc: 1.000 (best 0.667)
In epoch 25, loss: 0.201, val acc: 0.750 (best 0.750), test acc: 1.000 (best 0.667)
In epoch 30, loss: 0.112, val acc: 0.750 (best 0.750), test acc: 1.000 (best 0.667)
In epoch 35, loss: 0.059, val acc: 0.750 (best 0.750), test acc: 1.000 (best 0.667)
In epoch 40, loss: 0.031, val acc: 0.750 (best 0.750), test acc: 1.000 (best 0.667)
In epoch 45, loss: 

In [ ]:
g_2 = g.to('cuda')

In [ ]:
g.device, g_2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
indices = torch.stack(g_2.edges())
indices

tensor([[0, 0, 0, 1, 1, 0, 1, 2, 3],
        [1, 2, 3, 3, 3, 0, 1, 2, 3]], device='cuda:0')

In [ ]:
N = g_2.num_nodes()
A = dglsp.spmatrix(indices, shape=(N, N))
A

SparseMatrix(indices=tensor([[0, 0, 0, 1, 1, 0, 1, 2, 3],
                             [1, 2, 3, 3, 3, 0, 1, 2, 3]], device='cuda:0'),
             values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0'),
             shape=(4, 4), nnz=9)

In [ ]:
A.shape

(4, 4)

In [ ]:
# identity need manully move to device
dglsp.identity(A.shape), dglsp.identity(A.shape).cuda()

(SparseMatrix(indices=tensor([[0, 1, 2, 3],
                              [0, 1, 2, 3]]),
              values=tensor([1., 1., 1., 1.]),
              shape=(4, 4), nnz=4),
 SparseMatrix(indices=tensor([[0, 1, 2, 3],
                              [0, 1, 2, 3]], device='cuda:0'),
              values=tensor([1., 1., 1., 1.], device='cuda:0'),
              shape=(4, 4), nnz=4))

## dgl message passing

In [ ]:
# multigraph test
import os
import dgl
import dgl.data
import torch
import torch.nn as nn
import torch.nn.functional as F
from dgl.nn import GraphConv

import numpy as np

u, v = torch.tensor([0, 0, 0, 1, 1]), torch.tensor([1, 2, 3, 3, 3])
g = dgl.graph((u, v))
print(g)
print(g.nodes())
print(g.edges())
print(g.edges(form='all'))
g = dgl.graph((u, v), num_nodes=4)

g.ndata['feat']=torch.tensor(np.random.rand(4,20), dtype=torch.float32)
g.ndata["label"]=torch.tensor(np.random.randint(0,2,(4,)))
g.ndata['train_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g.ndata['val_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g.ndata['test_mask']=torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
g = dgl.add_self_loop(g)



class GCN(nn.Module):
    def __init__(self, in_feats, h_feats, num_classes):
        super(GCN, self).__init__()
        self.conv1 = GraphConv(in_feats, h_feats)
        self.conv2 = GraphConv(h_feats, num_classes)

    def forward(self, g, in_feat):
        h = self.conv1(g, in_feat)
        h = F.relu(h)
        h = self.conv2(g, h)
        return h


def train(g, model):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    best_val_acc = 0
    best_test_acc = 0

    features = g.ndata["feat"]
    labels = g.ndata["label"]
    train_mask = g.ndata["train_mask"]
    val_mask = g.ndata["val_mask"]
    test_mask = g.ndata["test_mask"]
    for e in range(100):
        # Forward
        logits = model(g, features)

        # Compute prediction
        pred = logits.argmax(1)

        # Compute loss
        # Note that you should only compute the losses of the nodes in the training set.
        loss = F.cross_entropy(logits[train_mask], labels[train_mask])

        # Compute accuracy on training/validation/test
        train_acc = (pred[train_mask] == labels[train_mask]).float().mean()
        val_acc = (pred[val_mask] == labels[val_mask]).float().mean()
        test_acc = (pred[test_mask] == labels[test_mask]).float().mean()

        # Save the best validation accuracy and the corresponding test accuracy.
        if best_val_acc < val_acc:
            best_val_acc = val_acc
            best_test_acc = test_acc

        # Backward
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if e % 5 == 0:
            print(
                f"In epoch {e}, loss: {loss:.3f}, val acc: {val_acc:.3f} (best {best_val_acc:.3f}), test acc: {test_acc:.3f} (best {best_test_acc:.3f})"
            )

# # train on cpu
# model = GCN(g.ndata["feat"].shape[1], 16, 2)
# train(g, model)

# train on gpu
g = g.to('cuda')
model = GCN(g.ndata["feat"].shape[1], 16, 2).to('cuda')
train(g, model)


Graph(num_nodes=4, num_edges=5,
      ndata_schemes={}
      edata_schemes={})
tensor([0, 1, 2, 3])
(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 3, 3]))
(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 3, 3]), tensor([0, 1, 2, 3, 4]))
In epoch 0, loss: 0.796, val acc: 0.667 (best 0.667), test acc: 1.000 (best 1.000)
In epoch 5, loss: 0.591, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 10, loss: 0.493, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 15, loss: 0.409, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 20, loss: 0.330, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 25, loss: 0.259, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 30, loss: 0.198, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 35, loss: 0.149, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 40, loss: 0.111, val acc: 0.333 (best 1.000), test acc: 0.000 (best 1.000)
In epoch 45, loss: 

# test pyG on gpu

In [ ]:
# from torch_geometric.datasets import Planetoid
# from torch_geometric.transforms import NormalizeFeatures

# dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())

# print()
# print(f'Dataset: {dataset}:')
# print('======================')
# print(f'Number of graphs: {len(dataset)}')
# print(f'Number of features: {dataset.num_features}')
# print(f'Number of classes: {dataset.num_classes}')

# data = dataset[0]  # Get the first graph object.

# print()
# print(data)
# print('===========================================================================================================')

# # Gather some statistics about the graph.
# print(f'Number of nodes: {data.num_nodes}')
# print(f'Number of edges: {data.num_edges}')
# print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
# print(f'Number of training nodes: {data.train_mask.sum()}')
# print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
# print(f'Has isolated nodes: {data.has_isolated_nodes()}')
# print(f'Has self-loops: {data.has_self_loops()}')
# print(f'Is undirected: {data.is_undirected()}')

In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 0, 0, 1],
                           [1, 2, 3, 3]], dtype=torch.long)

feat = torch.tensor(np.random.rand(4,20), dtype=torch.float32)
label = torch.tensor(np.random.randint(0,2,(4,)))

data = Data(x=feat, edge_index=edge_index, y=label)
data.num_classes=2


data.train_mask = torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
data.val_mask = torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)
data.test_mask = torch.tensor(np.random.randint(0,2,(4,)), dtype=torch.bool)

In [ ]:
data

Data(x=[4, 20], edge_index=[2, 4], y=[4], num_classes=2, train_mask=[4], val_mask=[4], test_mask=[4])

In [ ]:
data.node_attrs()

['train_mask', 'x', 'val_mask', 'y', 'test_mask']

In [ ]:
data.num_features

20

In [ ]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


class GCN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        torch.manual_seed(1234567)
        self.conv1 = GCNConv(data.num_features, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, data.num_classes)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = x.relu()
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return x

model = GCN(hidden_channels=16)
print(model)

GCN(
  (conv1): GCNConv(20, 16)
  (conv2): GCNConv(16, 2)
)


In [ ]:
model = GCN(hidden_channels=16)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

def train():
      model.train()
      optimizer.zero_grad()  # Clear gradients.
      out = model(data.x, data.edge_index)  # Perform a single forward pass.
      loss = criterion(out[data.train_mask], data.y[data.train_mask])  # Compute the loss solely based on the training nodes.
      loss.backward()  # Derive gradients.
      optimizer.step()  # Update parameters based on gradients.
      return loss


# # train on cpu
# for epoch in range(1, 5):
#     loss = train()
#     print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}')


# train on gpu
data = data.to('cuda')
model = model.to('cuda')
for epoch in range(1, 5):
    loss = train()
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}')

Epoch: 001, Loss: 1.3099
Epoch: 002, Loss: 1.4581
Epoch: 003, Loss: 0.9178
Epoch: 004, Loss: 0.7099


In [ ]:
next(model.parameters()).device

device(type='cuda', index=0)